name: ecommerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  coolicons: ^1.0.0
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  dart_code_metrics: ^4.6.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/images/logo_lockup_flutter_vertical.png
  color_dark: "#042a49"
  image_dark: assets/images/logo_lockup_flutter_vertical_wht.png
  fullscreen: true
